/**
 * Agent commission (FairPlay v5.9 §13) — how lobby rake is split with promoters.
 *
 * Two levels, never more:
 *
 *   Platform → Agent A (30% of lobby rake)
 *                └── Sub-Agent B (5–25%, a rate A sets and owns; B is terminal)
 *
 * A's 30% is the whole agent pool: whatever B takes comes OUT of A's share, not the platform's, so
 * the platform always keeps 70% before VIP linkage. The VIP uplift (V4 +10%, V5 +20%) is applied to
 * each tier's own portion independently and is paid FROM the platform's share — it is funded by the
 * extra volume those players generate.
 *
 * The hard boundary enforced here: commission is payable ONLY on PLATFORM lobby rake. League table
 * rake belongs 100% to the league and an agent has no claim on a cent of it (`commissionFor`
 * returns zero for league tables, and the test asserts it).
 */

export const PLATFORM_BASE_RATE_BPS = 3000; // A's 30% of lobby rake
export const SUB_AGENT_MIN_BPS = 500; // 5%
export const SUB_AGENT_MAX_BPS = 2500; // 25%
/** A must always retain at least 5% — so B's ceiling is A's rate − 5%. */
export const AGENT_MIN_RETAINED_BPS = 500;

export type VipLinkTier = 'NONE' | 'V4' | 'V5';

/** VIP linkage multipliers, in basis points (10000 = ×1.0). Ongoing, not one-time. */
export const VIP_LINK_BPS: Readonly<Record<VipLinkTier, number>> = {
  NONE: 10000,
  V4: 11000, // ×1.10
  V5: 12000, // ×1.20
};

export type TableType = 'PLATFORM' | 'LEAGUE';

export interface CommissionInput {
  /** Rake generated by the hand, in micro-units. */
  rake: number;
  tableType: TableType;
  /** The sub-agent's rate, if the player was referred by a sub-agent. */
  subAgentRateBps?: number;
  /** The referred player's VIP standing, for the linkage uplift. */
  vipLink?: VipLinkTier;
}

export interface CommissionSplit {
  /** The platform's retained share. */
  platform: number;
  /** Agent A's commission. */
  agent: number;
  /** Sub-agent B's commission (0 when the player is direct under A). */
  subAgent: number;
  /** Extra paid out due to VIP linkage — comes from the platform's share. */
  vipUplift: number;
}

export class CommissionRuleError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CommissionRuleError';
  }
}

/** B's rate must be 5–25% AND leave A at least 5% of the 30% pool. */
export function assertValidSubAgentRate(rateBps: number): void {
  if (rateBps < SUB_AGENT_MIN_BPS || rateBps > SUB_AGENT_MAX_BPS) {
    throw new CommissionRuleError(`sub-agent rate must be 5%–25%, got ${rateBps / 100}%`);
  }
  if (rateBps > PLATFORM_BASE_RATE_BPS - AGENT_MIN_RETAINED_BPS) {
    throw new CommissionRuleError(
      `sub-agent rate cannot exceed ${(PLATFORM_BASE_RATE_BPS - AGENT_MIN_RETAINED_BPS) / 100}% — the agent must retain 5%`,
    );
  }
}

/**
 * Split a hand's rake between platform, agent and sub-agent.
 * Every branch sums to exactly `rake` — no cent invented, none lost.
 */
export function commissionFor(input: CommissionInput): CommissionSplit {
  // League rake is untouchable: 100% stays with the league, agents get nothing.
  if (input.tableType === 'LEAGUE') {
    return { platform: 0, agent: 0, subAgent: 0, vipUplift: 0 };
  }
  if (input.rake <= 0) return { platform: 0, agent: 0, subAgent: 0, vipUplift: 0 };

  const linkBps = VIP_LINK_BPS[input.vipLink ?? 'NONE'];

  // Base portions out of A's 30% pool.
  const agentPool = Math.floor((input.rake * PLATFORM_BASE_RATE_BPS) / 10000);
  let baseSubAgent = 0;
  let baseAgent = agentPool;

  if (input.subAgentRateBps !== undefined) {
    assertValidSubAgentRate(input.subAgentRateBps);
    baseSubAgent = Math.floor((input.rake * input.subAgentRateBps) / 10000);
    // A keeps its rate minus B's — B's cut comes out of A, never out of the platform.
    baseAgent = Math.floor((input.rake * (PLATFORM_BASE_RATE_BPS - input.subAgentRateBps)) / 10000);
  }

  // VIP linkage lifts each tier's OWN portion independently; the uplift is funded by the platform.
  const agent = Math.floor((baseAgent * linkBps) / 10000);
  const subAgent = Math.floor((baseSubAgent * linkBps) / 10000);
  const vipUplift = agent - baseAgent + (subAgent - baseSubAgent);
  const platform = input.rake - agent - subAgent;

  return { platform, agent, subAgent, vipUplift };
}
