/**
 * The 6-step verifier, running in the player's browser (FairPlay v6.0 UltraFair).
 *
 * This is deliberately a re-implementation rather than a call to the server. Asking
 * the platform "was this hand fair?" and printing its answer proves nothing — the
 * whole point of provable fairness is that the player recomputes the hashes
 * themselves and needs to trust nobody. Every value below is public round data;
 * none of it is taken on faith.
 *
 * It therefore has to match game-server/src/fairness/ exactly. A drift would tell
 * an honest player their hand was rigged, which is the worst failure this feature
 * has — so the port is covered by tests against vectors generated by the real
 * server functions, in fairness.test.ts.
 *
 * Async throughout because Web Crypto's digest is async. crypto.subtle needs a
 * secure context; on plain http it is undefined, which is reported rather than
 * allowed to look like a verification failure.
 */

export interface ProofNode {
  hash: string;
  /** true if the sibling sits to the right of the current node. */
  right: boolean;
}

export interface SeatedClientSeed {
  seatOrder: number;
  clientSeed: string;
}

export interface RoundVerificationData {
  roundId: string;
  serverSeed: string;
  serverCommit: string;
  allClientSeeds: string;
  futureBlockHash: string;
  finalSeed: string;
  cards: string[];
  timestamp: number;
  roundHash: string;
  merkleProof: ProofNode[];
  merkleRoot: string;
  seatedClientSeeds: SeatedClientSeed[];
}

export type StepId = 1 | 2 | 3 | 4 | 5 | 6;

export interface StepResult {
  step: StepId;
  pass: boolean;
  /** What the player's own machine computed. */
  computed: string;
  /** What the round data claims. Equal to `computed` when the step passes. */
  expected: string;
}

export interface VerificationResult {
  steps: StepResult[];
  allPass: boolean;
}

// ─── primitives — must mirror node:crypto's behaviour exactly ─────────────────

function requireSubtle(): SubtleCrypto {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) {
    throw new Error(
      'Web Crypto is unavailable. Verification needs a secure context (https).',
    );
  }
  return subtle;
}

function toHex(bytes: Uint8Array): string {
  let out = '';
  for (const b of bytes) out += b.toString(16).padStart(2, '0');
  return out;
}

/**
 * Decode a hex digest, rejecting anything malformed.
 *
 * The naive version writes NaN — silently 0 — for any non-hex pair, which would
 * make a corrupt Merkle proof hash to a plausible-looking wrong value and read as
 * "this round was tampered with". A verifier must not manufacture evidence of
 * fraud out of a malformed input; failing loudly is the only honest option.
 */
function fromHex(hex: string): Uint8Array {
  if (hex.length % 2 !== 0 || !/^[0-9a-fA-F]*$/.test(hex)) {
    throw new Error(`not a hex digest: ${hex.slice(0, 24)}…`);
  }
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

/** SHA-256 of a UTF-8 string, hex — matches createHash('sha256').update(s).digest('hex'). */
async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  return toHex(new Uint8Array(await requireSubtle().digest('SHA-256', data)));
}

/** SHA-256 of raw bytes, returned as bytes — used by the seeded RNG's pool. */
async function sha256Raw(input: string): Promise<Uint8Array> {
  const data = new TextEncoder().encode(input);
  return new Uint8Array(await requireSubtle().digest('SHA-256', data));
}

// ─── the seed pipeline ───────────────────────────────────────────────────────

export const serverCommitOf = (serverSeed: string): Promise<string> => sha256Hex(serverSeed);

/** all_client_seeds = SHA256(C1 ‖ C2 ‖ … ‖ Cn), concatenated in seat order. */
export function mergeClientSeeds(seeds: readonly SeatedClientSeed[]): Promise<string> {
  const ordered = [...seeds].sort((a, b) => a.seatOrder - b.seatOrder).map((s) => s.clientSeed);
  return sha256Hex(ordered.join(''));
}

/** final_seed = SHA256(server_seed + all_client_seeds + future_block_hash + round_id). */
export function computeFinalSeed(
  serverSeed: string,
  allClientSeeds: string,
  futureBlockHash: string,
  roundId: string,
): Promise<string> {
  return sha256Hex(serverSeed + allClientSeeds + futureBlockHash + roundId);
}

/** round_hash — the 7-field digest of a whole round. Field order is the contract. */
export function computeRoundHash(input: {
  roundId: string;
  serverCommit: string;
  allClientSeeds: string;
  futureBlockHash: string;
  finalSeed: string;
  cards: readonly string[];
  timestamp: number;
}): Promise<string> {
  return sha256Hex(
    input.roundId +
      input.serverCommit +
      input.allClientSeeds +
      input.futureBlockHash +
      input.finalSeed +
      JSON.stringify(input.cards) +
      input.timestamp.toString(),
  );
}

// ─── the deterministic shuffle ───────────────────────────────────────────────

/**
 * Counter-based hash stream feeding Fisher-Yates.
 *
 * Refill boundary, byte order and rejection sampling all have to match the server
 * exactly: consume one uint32 too many, or read little-endian, and every deck
 * diverges from the second card onward.
 */
class SeededRng {
  private blockIndex = 0;
  private pool = new Uint8Array(0);
  private offset = 0;
  private readonly seed: string;

  // Written out rather than a TS parameter property so this module stays plain
  // strippable TypeScript. Anyone auditing a hand should be able to run this file
  // directly — under `node fairness.ts`, in a REPL, anywhere — without a build
  // step standing between them and checking the platform's arithmetic.
  constructor(seed: string) {
    this.seed = seed;
  }

  private async refill(): Promise<void> {
    this.pool = await sha256Raw(`${this.seed}:${this.blockIndex}`);
    this.blockIndex += 1;
    this.offset = 0;
  }

  private async nextUint32(): Promise<number> {
    if (this.offset + 4 > this.pool.length) await this.refill();
    // Big-endian, matching Buffer.readUInt32BE.
    const view = new DataView(this.pool.buffer, this.pool.byteOffset, this.pool.byteLength);
    const value = view.getUint32(this.offset, false);
    this.offset += 4;
    return value;
  }

  /** Uniform integer in [0, n) via rejection sampling — no modulo bias. */
  async nextIntBelow(n: number): Promise<number> {
    const limit = Math.floor(0x1_0000_0000 / n) * n;
    let x = await this.nextUint32();
    while (x >= limit) x = await this.nextUint32();
    return x % n;
  }
}

const RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A'] as const;
const SUITS = ['c', 'd', 'h', 's'] as const;

export function standardDeck(): string[] {
  const deck: string[] = [];
  for (const rank of RANKS) {
    for (const suit of SUITS) deck.push(`${rank}${suit}`);
  }
  return deck;
}

export async function shuffle(deck: readonly string[], seed: string): Promise<string[]> {
  const out = [...deck];
  const rng = new SeededRng(seed);
  for (let i = out.length - 1; i >= 1; i--) {
    const j = await rng.nextIntBelow(i + 1);
    const tmp = out[i]!;
    out[i] = out[j]!;
    out[j] = tmp;
  }
  return out;
}

export const shuffledDeck = (seed: string): Promise<string[]> => shuffle(standardDeck(), seed);

// ─── the Merkle proof ────────────────────────────────────────────────────────

/** SHA-256 over the concatenated RAW bytes of two hex digests — not their text. */
async function hashPair(a: string, b: string): Promise<string> {
  const left = fromHex(a);
  const right = fromHex(b);
  const joined = new Uint8Array(left.length + right.length);
  joined.set(left, 0);
  joined.set(right, left.length);
  return toHex(new Uint8Array(await requireSubtle().digest('SHA-256', joined)));
}

/**
 * Walk the proof path and return the root it rebuilds.
 *
 * Returns the computed root rather than a boolean, so the caller can show the
 * player what their own machine derived next to what the platform published. A
 * bare `false` would be a verdict; two roots side by side are evidence.
 */
export async function verifyMerkleProof(
  leaf: string,
  proof: readonly ProofNode[],
): Promise<string> {
  let computed = leaf;
  for (const node of proof) {
    computed = node.right
      ? await hashPair(computed, node.hash)
      : await hashPair(node.hash, computed);
  }
  return computed;
}

// ─── the verifier ────────────────────────────────────────────────────────────

/**
 * Run all six steps.
 *
 * Every step returns what was computed alongside what was claimed, so a failure
 * shows the player the two hashes rather than just the word "failed" — that
 * difference is the evidence, and evidence is the entire product here.
 */
export async function verifyRound(d: RoundVerificationData): Promise<VerificationResult> {
  const steps: StepResult[] = [];

  const commit = await serverCommitOf(d.serverSeed);
  steps.push({ step: 1, pass: commit === d.serverCommit, computed: commit, expected: d.serverCommit });

  const finalSeed = await computeFinalSeed(
    d.serverSeed,
    d.allClientSeeds,
    d.futureBlockHash,
    d.roundId,
  );
  steps.push({
    step: 2,
    pass: finalSeed === d.finalSeed,
    computed: finalSeed,
    expected: d.finalSeed,
  });

  const merged = await mergeClientSeeds(d.seatedClientSeeds);
  steps.push({
    step: 3,
    pass: merged === d.allClientSeeds,
    computed: merged,
    expected: d.allClientSeeds,
  });

  // Step 4 compares whole decks; the hashes above are per-value, so summarise the
  // deck as its first few cards — enough to see it differs, short enough to read.
  const deck = await shuffledDeck(d.finalSeed);
  const deckMatches = deck.length === d.cards.length && deck.every((c, i) => c === d.cards[i]);
  steps.push({
    step: 4,
    pass: deckMatches,
    computed: deck.slice(0, 5).join(' '),
    expected: d.cards.slice(0, 5).join(' '),
  });

  const roundHash = await computeRoundHash({
    roundId: d.roundId,
    serverCommit: d.serverCommit,
    allClientSeeds: d.allClientSeeds,
    futureBlockHash: d.futureBlockHash,
    finalSeed: d.finalSeed,
    cards: d.cards,
    timestamp: d.timestamp,
  });
  steps.push({
    step: 5,
    pass: roundHash === d.roundHash,
    computed: roundHash,
    expected: d.roundHash,
  });

  const root = await verifyMerkleProof(d.roundHash, d.merkleProof);
  steps.push({ step: 6, pass: root === d.merkleRoot, computed: root, expected: d.merkleRoot });

  return { steps, allPass: steps.every((s) => s.pass) };
}
