import { describe, it, expect } from 'vitest';
import vector from './__fixtures__/round-vector.json';
import {
  verifyRound,
  serverCommitOf,
  computeFinalSeed,
  mergeClientSeeds,
  computeRoundHash,
  shuffledDeck,
  standardDeck,
  type RoundVerificationData,
} from './fairness';

/**
 * Cross-implementation check.
 *
 * The fixture was generated by game-server/src/fairness — the real production
 * functions — and the server's own verifier accepts it. So these tests are not
 * checking this file against itself; they are pinning it to the server's
 * arithmetic.
 *
 * That pinning is the whole point. This module re-implements the hashing so a
 * player can verify a hand without trusting the platform, which means any drift
 * between the two shows up as the page telling an honest player their hand was
 * rigged. Regenerate the fixture — not the expectations — if the seed pipeline
 * ever legitimately changes.
 */

const round = vector as RoundVerificationData;

describe('the 6-step verifier, against a server-generated round', () => {
  it('passes all six steps', async () => {
    const result = await verifyRound(round);
    const failed = result.steps.filter((s) => !s.pass).map((s) => s.step);

    expect(failed).toEqual([]);
    expect(result.allPass).toBe(true);
  });

  it('reproduces each value the server computed', async () => {
    expect(await serverCommitOf(round.serverSeed)).toBe(round.serverCommit);
    expect(await mergeClientSeeds(round.seatedClientSeeds)).toBe(round.allClientSeeds);
    expect(
      await computeFinalSeed(
        round.serverSeed,
        round.allClientSeeds,
        round.futureBlockHash,
        round.roundId,
      ),
    ).toBe(round.finalSeed);
    expect(await computeRoundHash(round)).toBe(round.roundHash);
  });

  it('reproduces the exact deck, in order', async () => {
    expect(await shuffledDeck(round.finalSeed)).toEqual(round.cards);
  });
});

describe('tamper detection', () => {
  /**
   * Each case must fail exactly the steps it should and no others. Over-failing
   * matters as much as under-failing: a step that trips on unrelated tampering
   * tells the player nothing about WHERE the round was altered, and the location
   * is the evidence.
   */
  const cases: { name: string; mutate: (r: RoundVerificationData) => RoundVerificationData; fails: number[] }[] = [
    {
      name: 'server swapped its seed after committing',
      mutate: (r) => ({ ...r, serverSeed: 'f'.repeat(64) }),
      fails: [1, 2],
    },
    {
      name: "a player's seed was dropped from the merge",
      mutate: (r) => ({ ...r, seatedClientSeeds: r.seatedClientSeeds.slice(1) }),
      fails: [3],
    },
    {
      name: 'the merged client seeds were altered',
      mutate: (r) => ({ ...r, allClientSeeds: 'e'.repeat(64) }),
      fails: [2, 3, 5],
    },
    {
      name: 'two dealt cards were swapped',
      mutate: (r) => ({ ...r, cards: [r.cards[1]!, r.cards[0]!, ...r.cards.slice(2)] }),
      fails: [4, 5],
    },
    {
      name: 'the round hash was rewritten',
      mutate: (r) => ({ ...r, roundHash: 'd'.repeat(64) }),
      fails: [5, 6],
    },
    {
      name: 'the on-chain root does not match',
      mutate: (r) => ({ ...r, merkleRoot: 'c'.repeat(64) }),
      fails: [6],
    },
    {
      // Step 5 only, and that is the design working rather than a gap. Step 6
      // checks the STORED round hash against the on-chain root; it does not
      // recompute it. So backdating alone is caught by step 5, and an attacker
      // who also rewrites the stored hash to match escapes step 5 but then fails
      // step 6, because the rewritten hash is not the one in the notarized tree.
      // Neither move survives both.
      name: 'the timestamp was backdated',
      mutate: (r) => ({ ...r, timestamp: r.timestamp - 86_400_000 }),
      fails: [5],
    },
  ];

  for (const { name, mutate, fails } of cases) {
    it(`catches: ${name}`, async () => {
      const result = await verifyRound(mutate(round));
      const failed = result.steps.filter((s) => !s.pass).map((s) => s.step);

      expect(failed).toEqual(fails);
      expect(result.allPass).toBe(false);
    });
  }
});

describe('failure reporting', () => {
  it('shows what was computed alongside what was claimed', async () => {
    const result = await verifyRound({ ...round, serverCommit: 'a'.repeat(64) });
    const step1 = result.steps.find((s) => s.step === 1)!;

    // The two hashes ARE the evidence — a bare "failed" proves nothing.
    expect(step1.pass).toBe(false);
    expect(step1.expected).toBe('a'.repeat(64));
    expect(step1.computed).not.toBe(step1.expected);
    expect(step1.computed).toMatch(/^[0-9a-f]{64}$/);
  });

  it('rejects a malformed proof rather than reporting tampering', async () => {
    // A corrupt hex digest must throw, not hash to a plausible wrong value and
    // read as fraud. Accusing an honest platform is as bad as clearing a guilty
    // one.
    await expect(
      verifyRound({ ...round, merkleProof: [{ hash: 'not-hex!!', right: true }] }),
    ).rejects.toThrow(/hex/i);
  });
});

describe('the deck itself', () => {
  it('starts from a canonical 52-card deck', () => {
    const deck = standardDeck();
    expect(deck).toHaveLength(52);
    expect(new Set(deck).size).toBe(52);
    expect(deck[0]).toBe('2c');
    expect(deck[51]).toBe('As');
  });

  it('is deterministic — same seed, same order', async () => {
    expect(await shuffledDeck('abc')).toEqual(await shuffledDeck('abc'));
  });

  it('is sensitive to the seed', async () => {
    expect(await shuffledDeck('abc')).not.toEqual(await shuffledDeck('abd'));
  });

  it('permutes rather than loses cards', async () => {
    const shuffled = await shuffledDeck(round.finalSeed);
    expect([...shuffled].sort()).toEqual([...standardDeck()].sort());
  });
});
